### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GalaxyXYZ888** [Ezzud/instify#2]
Idk if you see this still and if you can help xd
But i have set everything up and it was working flawlessly, but today randonmly it stopped work without me doing anything.
So, if you can see my error and know hot to solve it i would be thankfull !
[CMD Error.txt](https://github.com/Ezzud/instify/files/9022013/CMD.Error.txt)

**Comment by Ezzud** [comment]
New Instagram API doesn't work anymore, project is outdated
